// Shows
export const GET_COUNTRIES = "GET_COUNTRIES";
export const SET_LOADING = "SET_LOADING";
export const GET_COUNTRIE_DETAIL = "GET_COUNTRIE_DETAIL";
export const CLEAR_COUNTRIE_DETAIL = "CLEAR_COUNTRIE_DETAIL";

// Theme
export const SET_DARK_THEME = "SET_DARK_THEME";
export const REMOVE_DARK_THEME = "REMOVE_DARK_THEME";
