// Shows
export const GET_COUNTRIES = "GET_COUNTRIES";
export const SET_LOADING = "SET_LOADING";
export const GET_COUNTRIE_DETAIL = "GET_COUNTRIE_DETAIL";
export const CLEAR_COUNTRIE_DETAIL = "CLEAR_COUNTRIE_DETAIL";

// Theme
export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";
