// Shows
export const GET_COUNTRIES = "GET_COUNTRIES";
export const SET_LOADING = "SET_LOADING";
export const GET_COUNTRIE_DETAIL = "GET_COUNTRIE_DETAIL";
export const CLEAR_COUNTRIE_DETAIL = "CLEAR_COUNTRIE_DETAIL";
export const FILTER_SEARCH_COUNTRIES = "FILTER_SEARCH_COUNTRIES";
export const FILTER_SELECT_COUNTRIES = "FILTER_SELECT_COUNTRIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";

// Theme
export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";
